In [7]:
import pandas as pd
import wrds
import pandas as pd
dsf=pd.read_csv('dsf.csv')
# Enter your WRDS credentials
username = 'navid_namazi'
password = 'W77w@UrxFZQ.9cR'

# Connect to WRDS with username and password
db = wrds.Connection(wrds_username=username, wrds_password=password)

# Example: Assuming dsf is your dataframe with a 'permno' column
# Query CRSP to get the ticker names for each permno
query = """
    SELECT permno, ticker
    FROM crsp.stocknames
    WHERE permno IN ({})
""".format(",".join(map(str, dsf['permno'].unique())))

tickers = db.raw_sql(query)

# Merge ticker names with your dataframe on 'permno'
dsf = dsf.merge(tickers, on='permno', how='left')

dsf.head()

Loading library list...
Done

,permno,date,cusip,bidlo,askhi,prc,vol,ret,bid,ask,shrout,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker
0,10026,2020-01-02,46603210,181.44,185.30,181.67999,88291.0,-0.014056,181.67000,181.70000,18900.0,1.0,1.0,185.30000,2300.0,-0.014056,181.67999,18900.0,3433751.811,JJSF
1,10026,2020-01-02,46603210,181.44,185.30,181.67999,88291.0,-0.014056,181.67000,181.70000,18900.0,1.0,1.0,185.30000,2300.0,-0.014056,181.67999,18900.0,3433751.811,JJSF
2,10026,2020-01-03,46603210,180.89,185.17,184.91000,71463.0,0.017779,184.89999,184.91000,18900.0,1.0,1.0,180.89000,1572.0,0.017779,184.91000,18900.0,3494799.000,JJSF
3,10026,2020-01-03,46603210,180.89,185.17,184.91000,71463.0,0.017779,184.89999,184.91000,18900.0,1.0,1.0,180.89000,1572.0,0.017779,184.91000,18900.0,3494799.000,JJSF
4,10026,2020-01-06,46603210,183.14,185.52,185.07001,70308.0,0.000865,184.77000,185.07001,18900.0,1.0,1.0,184.17999,1764.0,0.000865,185.07001,18900.0,3497823.189,JJSF

In [ ]:

df=dsf[dsf['prc']<0][['permno', 'ticker', 'date', 'prc','ask','bid']]
df

         permno ticker        date     prc
23790     10232   ESBK  2020-01-28 -16.475
23791     10232   ESBK  2020-01-28 -16.475
23792     10232   ESBK  2020-01-28 -16.475
24036     10232   ESBK  2020-05-26 -11.945
24037     10232   ESBK  2020-05-26 -11.945
...         ...    ...         ...     ...
5643758   93367   PSCD  2020-10-08 -69.780
5643759   93367   PSCD  2020-10-08 -69.780
5643928   93367   XLYS  2020-12-30 -82.075
5643929   93367   PSCD  2020-12-30 -82.075
5643930   93367   PSCD  2020-12-30 -82.075

[68929 rows x 4 columns]

In [13]:
#get unique tickers in df and print them all
unique_tickers = df['ticker'].unique()
unique_tickers = df['ticker'].unique()
print(unique_tickers)

<StringArray>
[ 'ESBK', 'HAVTA',   'HVT',  'DJCO',  'TWMC',  'KSPN',  'PTSI',  'PAMT',
  'CYAN',    <NA>,
 ...
  'XLFS',  'PSCF',  'XLIS',  'PSCI',  'XLPS',  'PSCC',  'XLUS',  'PSCU',
  'XLYS',  'PSCD']
Length: 1646, dtype: string