In [22]:
import pandas as pd
import wrds

dsf = pd.read_parquet('wrds_extracts\\run_20250914_133747\\dsf.parquet')

# Enter your WRDS credentials
username = 'navid_namazi'
password = 'W77w@UrxFZQ.9cR'

# Connect to WRDS with username and password
db = wrds.Connection(wrds_username=username, wrds_password=password)

# Query CRSP to get the ticker names and company names for each permno
query = """
    SELECT permno, ticker, comnam
    FROM crsp.stocknames
    WHERE permno IN ({})
""".format(",".join(map(str, dsf['permno'].unique())))

tickers = db.raw_sql(query)

# Merge ticker and company names with your dataframe on 'permno'
dsf = dsf.merge(tickers, on='permno', how='left')

dsf.head()

Loading library list...
Done

,cusip,permno,date,bidlo,askhi,prc,vol,ret,bid,ask,...,cfacpr,cfacshr,openprc,numtrd,retx,adj_prc,adj_shrout,adj_mktcap,ticker,comnam
0,46603210,10026,2020-01-02,181.4400,185.30,181.67999,88291.0,-0.014056,181.67,181.70,...,1.0,1.0,185.3000,2300.0,-0.014056,181.67999,18900.0,3433751.811,JJSF,J & J SNACK FOODS CORP
1,46603210,10026,2020-01-02,181.4400,185.30,181.67999,88291.0,-0.014056,181.67,181.70,...,1.0,1.0,185.3000,2300.0,-0.014056,181.67999,18900.0,3433751.811,JJSF,J & J SNACK FOODS CORP
2,29402E10,10028,2020-01-02,1.3601,1.38,1.38000,4400.0,0.022222,1.37,1.39,...,1.0,1.0,1.3601,NaN,0.022222,1.38000,26924.0,37155.120,MINT,CANYON STATE CORP
3,29402E10,10028,2020-01-02,1.3601,1.38,1.38000,4400.0,0.022222,1.37,1.39,...,1.0,1.0,1.3601,NaN,0.022222,1.38000,26924.0,37155.120,MINT,AMERICAN PACIFIC MINT INC
4,29402E10,10028,2020-01-02,1.3601,1.38,1.38000,4400.0,0.022222,1.37,1.39,...,1.0,1.0,1.3601,NaN,0.022222,1.38000,26924.0,37155.120,MINT,AMERICAN PACIFIC MINT INC

In [38]:
df=dsf[(dsf['cfacshr']==0)|(dsf['cfacpr']==0)][['permno', 'ticker', 'date', 'prc','ask','bid','cfacpr','cfacshr','comnam']]
df['permno'].value_counts()

permno
12350    2530
Name: count, dtype: int64

In [ ]:

df=dsf[dsf['prc']<0][['permno', 'ticker','comnam', 'date', 'prc','ask','bid','cfacpr','cfacshr']]
display(df)

#first count the number of rows in each group
group_counts = df['permno'].value_counts()
print(group_counts )
df = df.groupby('permno').filter(lambda x: len(x) <= 0.01 * len(dsf[dsf['permno'] == x.name]))
group_counts = df['permno'].value_counts()
print(group_counts )


df

,permno,ticker,comnam,date,prc,ask,bid,cfacpr,cfacshr
130,10294,HAVTA,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
131,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
132,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
133,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
134,10294,HVT,HAVERTY FURNITURE COS INC,2020-01-02,-19.550,20.54,18.56,1.0,1.0
...,...,...,...,...,...,...,...,...,...
5658263,89576,VBFC,VILLAGE BANK AND TRUST FINL CORP,2020-12-31,-34.625,36.00,33.25,1.0,1.0
5658264,89576,VBFC,VILLAGE BANK AND TRUST FINL CORP,2020-12-31,-34.625,36.00,33.25,1.0,1.0
5659337,90636,KFFB,KENTUCKY FIRST FEDERAL BANCORP,2020-12-31,-6.410,6.49,6.33,1.0,1.0
5662220,93291,SBM,PROSHARES TRUST,2020-12-31,-12.370,12.39,12.35,0.2,0.2
5662221,93291,SBM,PROSHARES TRUST,2020-12-31,-12.370,12.39,12.35,0.2,0.2

permno
62958    1211
75069    1180
64899    1098
61508    1062
10294    1056
         ...
18159       1
17067       1
20127       1
19428       1
20291       1
Name: count, Length: 1250, dtype: int64
permno
84820    30
75754    20
89812    20
83410    20
75415    16
         ..
91609     1
15946     1
18521     1
19171     1
19525     1
Name: count, Length: 222, dtype: int64

,permno,ticker,comnam,date,prc,ask,bid,cfacpr,cfacshr
390,11292,ICCC,IMMUCELL CORP,2020-01-02,-5.08,5.15,5.01,1.0,1.0
391,11292,ICCC,IMMUCELL CORP,2020-01-02,-5.08,5.15,5.01,1.0,1.0
392,11292,ICCC,IMMUCELL CORP,2020-01-02,-5.08,5.15,5.01,1.0,1.0
7684,18514,BRPM,B RILEY PRINCIPAL MERGER CORP,2020-01-02,-10.05,10.09,10.01,1.0,1.0
7685,18514,BRPM,B RILEY PRINCIPAL MERGER CORP,2020-01-02,-10.05,10.09,10.01,1.0,1.0
...,...,...,...,...,...,...,...,...,...
5554550,17030,LFEQ,VANECK E T F TRUST,2020-12-24,-34.87,34.89,34.85,1.0,1.0
5570458,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5
5570459,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5
5570460,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5
5570461,92352,EFU,PROSHARES TRUST,2020-12-24,-13.19,13.21,13.17,0.5,0.5

In [26]:
df['comnam'].unique()

<StringArray>
[       'HAVERTY FURNITURE COS INC',                   'CYANOTECH CORP',
                    'IMMUCELL CORP',   'AIR TRANSPORTATION HLDG CO INC',
                        'AIR T INC',              'S G O C O GROUP LTD',
                  'T R O O P S INC', 'FIRST TR EXCH TRD ALPHADEX FD II',
                      'F Q F TRUST',          'A G F INVESTMENTS TRUST',
 ...
        'TURMERIC ACQUISITION CORP', 'F G NEW AMERICA ACQUISITION CORP',
                        'OPPFI INC',       'YELLOWSTONE ACQUISITION CO',
           'SKY HARBOUR GROUP CORP',         'TEKKORP DIGITAL ACQ CORP',
          'BULL HORN HOLDINGS CORP', 'COEPTIS THERAPEUTICS HOLDINGS IN',
       'SPARTACUS ACQUISITION CORP',     'EUCRATES BIOMEDICAL ACQ CORP']
Length: 1086, dtype: string